FROM node:14.16.0-alpine3.10 as build-stage

# Set working directory
WORKDIR /app

COPY package*.json ./
COPY vue.config.js ./
RUN npm install

COPY ./ .
RUN npm run build

FROM nginx:stable-alpine as production-stage

RUN mkdir /app
COPY --from=build-stage /app/dist /app
COPY nginx.conf /etc/nginx/nginx.conf

# Serve
EXPOSE 80