version: '3.7'

networks:
  general_network:
    name: general_network

services:
  # # Portal
  # client:
  #   build: ./client

  # API server
  server:
    build: ./server
    ports:
      - '5000:8080'
    env_file: ./server/server.env
    networks:
      - general_network

  # Proxy
  proxy:
    container_name: proxy
    image: nginx:stable-alpine
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/uwsgi_params:/etc/nginx/uwsgi_params:ro
    ports:
      - "80:80"
    networks:
      - general_network