version: '3.7'

networks:
  twitter_network:
    name: twitter_network

volumes:
    postgres:

services:
  # Database
  database:
    container_name: postgres-database
    image: postgres:14.5-alpine
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - ./server/sql.env
    volumes:
      - postgres:/data/postgres
    networks:
      - twitter_network

  # # Portal
  # client:
  #   build: ./client

  # API server
  server:
    build: ./server
    restart: always
    ports:
      - '5000:8080'
    env_file: 
      - ./server/server.env
      - ./server/sql.env
    depends_on:
      - database
    networks:
      - twitter_network

  # Proxy
  proxy:
    container_name: proxy
    image: nginx:stable-alpine
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/uwsgi_params:/etc/nginx/uwsgi_params:ro
    ports:
      - "80:80"
    networks:
      - twitter_network