version: '3.7'

networks:
  general_network:
    name: general_network

services:
  # Database
  database:
    container_name: mysql-database
    image: mysql:8.0.30-debian
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - '3300:3306'
    env_file:
      - ./server/mysql.env
    networks:
      - general_network

  # # Portal
  # client:
  #   build: ./client

  # API server
  server:
    build: ./server
    restart: always
    ports:
      - '5000:8080'
    env_file: 
      - ./server/server.env
      - ./server/mysql.env
    depends_on:
      - database
    networks:
      - general_network

  # Proxy
  proxy:
    container_name: proxy
    image: nginx:stable-alpine
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/uwsgi_params:/etc/nginx/uwsgi_params:ro
    ports:
      - "80:80"
    networks:
      - general_network