# Generated by Django 3.0.3 on 2020-08-22 15:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twitter', '0004_auto_20200822_2202'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follow',
            new_name='FollowConnect',
        ),
    ]
