FROM python:3.9-alpine as app-stage

WORKDIR /app

# Install utils
RUN apk add --update --no-cache --virtual .tmp gcc libc-dev linux-headers musl-dev libffi-dev
RUN apk add --no-cache mariadb-dev mariadb-client mariadb-connector-c
RUN pip install -U cffi pip setuptools

# Install requirements
COPY ./requirements.txt ./requirements.txt
RUN pip3 install --no-cache-dir -r ./requirements.txt

RUN rm ./requirements.txt
RUN apk del .tmp

# Copy Source
COPY . /app

RUN chmod +x /app/entrypoint.sh

# Create static volume
RUN mkdir -p /vol/static

RUN adduser -D user
RUN chown -R user:user /vol
RUN chmod -R 755 /vol/static

# Add user
USER user

EXPOSE 8080

CMD [ "sh", "/app/entrypoint.sh" ]