FROM python:3.8-alpine as app-stage

WORKDIR /app

# Install utils
RUN apk add --update --no-cache --virtual .tmp gcc libc-dev linux-headers musl-dev libffi-dev mariadb-dev
RUN pip install -U cffi pip setuptools

# Install requirements
COPY ./requirements.txt ./requirements.txt
RUN pip3 install --no-cache-dir -r ./requirements.txt

RUN rm ./requirements.txt
RUN apk del .tmp

# Copy Source
COPY . /app

# Create static volume
RUN mkdir -p /vol/static

# Add user
USER daemon

EXPOSE 8080

CMD ["uwsgi", "--ini" , "/app/uwsgi.ini","--module","server.wsgi"]